### ISSUE TITLE
Getting Timings

### ISSUE THREAD

**Issue by adamhall** [trey0/zmdp#2]
Great package! I was wondering if there is a way to output various timings. e.g. how long it takes to load in data, how long it takes to initialize, how long it takes to solve etc. 

I feel like the benchmark capability does this in some way, but I'm not sure how. I'm wondering if there are any options for zmdp solve to output such timings.

I think setting debug mode to 1 does what I'm looking for but I'm not sure how to interpret it...

**Comment by trey0** [comment]
You got it. The 'zmdp benchmark' command is similar to 'zmdp solve' but periodically interrupts the solver to report statistics such as number of updates performed, elapsed time, policy performance in simulation, and upper and lower bounds on the quality of the policy.

The elapsed time reported by 'zmdp benchmark' excludes time spent in loading in data and initializing bounds in order to focus on the iterative updates that are the main difference between different solver algorithms. It would be easy to log extra timing information by tweaking TestDriver.cc.

The debugLevel parameter isn't really connected to timing. It's more for debugging any weird behavior and understanding the internals of the algorithms.
